### ISSUE TITLE
Takes Photo when presented and -- master branch

### ISSUE THREAD

**Issue by syky27** [hyperoslo/ImagePicker#103]
Hi!
I forked your awesome ImagePicker from **master**, because I need it to bend the functionality little bit for purpose of app I am developing. And I found two related bugs.

**1. ImagePicker takes Photo on when presented**
This was really weird so I dug deeper and found out that for some reason a notification with volume did change has been posted, and it makes ImagePicker to take picture.

**2. While taking pictures using button to change volume ImagesPicker ignores imageLimit**
And this is second bug. 

I am not really sure if you guys are aware of these bugs or not. But considering that you are running two branches `master` and `development` I though that this is something that should not be in master.

I would try to find origins of these problems but I am in hurry to finish the project I am working on, so I am just reporting these issues.

Anyway thanks for awesome contribution to community!

**Comment by zenangst** [comment]
Hey @syky27, `master` for us has been like `develop`. This is where we put all the new things that could and should potentially get into the next release. We therefor advice anyone using `ImagePicker` to use the latest release version as we consider that one to be stable. This is of course is something that coulda/woulda/shoulda be changed to avoid confusion in the future. But for the time being, you shouldn't consider `master` to be stable. The latest stable version of `ImagePicker` is `https://github.com/hyperoslo/ImagePicker/releases/tag/1.1`.
We went with this approach because people shouldn't have to specify a specific branch in their pod or cart file and it makes it easier for us and others when using `ImagePicker` as a dependency in pod and cart files.

Thanks for reporting your findings, we will have a look and see what we can do to fix them before the next release. Anyone is of course free to make PR to fix said bugs and we would be super happy if that happened.

Sorry for any confusion that this may have caused.

Stay awesome and thanks for supporting `ImagePicker`.

**Comment by fnakstad** [comment]
The first bug you mention sounds like the same one I ran into, but was fixed in #106.

**Comment by aashishdhawan** [comment]
@syky27 Both these issues have been fixed. Please try latest version 1.3.0
