### ISSUE TITLE
Do not save captured photos

### ISSUE THREAD

**Issue by jpodcedensek** [hyperoslo/ImagePicker#117]
Hi, is there a way to prevent new photos being saved to device or if that is not available, to delete new photos when no longer needed in app?

**Comment by aashishdhawan** [comment]
@jpodcedensek That feature is not available yet but we might consider that in future release. We'll keep you posted here.

**Comment by onmyway133** [comment]
@jpodcedensek Hi, `ImagePicker` is based on simple design of `PHAsset` management. When the photo is captured and saved to Library as `PHAsset`, the list of `PHAsset` is updated automatically and the gallery is refreshed. 

This can be done by treating newly captured photo as `PHAsset` or saving them to another custom album. Feel free to submit a PR. Closing this for now

**Comment by sryze** [comment]
I too think that photo saving should be optional. For example, my app's users wouldn't want to keep pictures taken with camera around, they upload them to the server (as attachments) and forget about them. 

I see two ways - make it optional to the developer (so that they can change whether to save or not), or optional to the user so that users can choose on their side whether to save to their photo library. Maybe make it like: quick tap to just add a picture, long press to take a picture *and* save it.

**Comment by robindirksen1** [comment]
@onmyway133 @sryze any news about this issue/feature?

**Comment by dcortright** [comment]
@onmyway133 I am also interested if this is still being planned? Or if a pull request is the better route to take?
