### ISSUE TITLE
How to update ImagePicker selected images after deleting images in wrapper lightbox

### ISSUE THREAD

**Issue by rx2130** [hyperoslo/ImagePicker#196]
Hi, I want to be able to delete images inside the wrapper lightbox as a preview feature in my app. So I set `LightboxConfig.DeleteButton.enabled = true`. While I could delete the images, the counter inside the camera shutter was not decreased, neither the highlight images were unhighlight. 

So I was wondering what's the best way to accomplish this? Right now I'm implementing `LightboxControllerDismissalDelegate` and doing the manual update in `lightboxControllerWillDismiss`. But I doubt this is the optimal way to achieve this feature. 

Thanks!

**Comment by aashishdhawan** [comment]
`ImagePicker` provides you the option to `resetAssets` which can be used to refresh UI of imagePicker after any update but in order to solve your problem you need to know which images were deleted from `LightBox` which unfortunately is a functionality not supported by `LightBox`. Therefore what you are trying to do is not possible with `ImagePicker+LightBox` combination without modification in code base. 

So for optimal solution if `LightBox` provides you deleted images we can use `resetAssets` to update `ImagePicker.`

We'll add this feature in our TODO list. Also we welcome new pull requests too. If you are able to solve this please create a PR, we'll review it gladly. 

Thanks.
