### ISSUE TITLE
Automatically dismiss if one picture only

### ISSUE THREAD

**Issue by JeevanThandi** [hyperoslo/ImagePicker#200]
Hi,

I've noticed that the experience is quite confusing if users are inputting one picture from the camera roll as they have to press "done" - it'd be great if once the user had selected an image - the control would auto dismiss. 

Thanks

**Comment by richardtop** [comment]
User may want to look at the picture in detail, then pick the best one. If control is being dismissed as soon as the user picked the image, it would be impossible to see, what has been selected.

**Comment by RamonGilabert** [comment]
As @richardtop said, it's kind of trying to generalize a case that might not make sense to generalize.

With that being said, you could make a PR with a configuration property or behavior that dismisses the Picker when you set it to true.

Say: `dismissWhenLimit` or something like that.

By now, though, I'm closing the issue, since it's not something we will actively work on! Feel free to reopen it or do a PR.
