### ISSUE TITLE
Supports swift 3?

### ISSUE THREAD

**Issue by slehyder** [hyperoslo/ImagePicker#203]
I have been reviewing and updating of the new xcode 8 and swift 3 several libraries have been unsupported wanted to know if you have it and how do I work with this updated support.

**Comment by RamonGilabert** [comment]
We will have it, maximum by the end of next week :)

**Comment by zenangst** [comment]
Yeah, as @RamonGilabert stated, all our oompa loompas are hard at work with migrating all our OSS to support Swift 3.

![raw](https://cloud.githubusercontent.com/assets/57446/18542319/90114414-7b2a-11e6-8ab7-6dbb1de97aae.gif)

**Comment by elprl** [comment]
Would strongly advise a separate branch for swift 2.3 and 3.0 for cocoapod users to pick:
  pod 'ImagePicker', :git => 'https://github.com/hyperoslo/ImagePicker.git', :branch => 'swift-2.2'
  pod 'ImagePicker', :git => 'https://github.com/hyperoslo/ImagePicker.git', :branch => 'swift-3.0'

**Comment by phucnd0604** [comment]
@elprl cannot find swift-3.0 git repo

**Comment by kwstasna** [comment]
Still not supported?

**Comment by zenangst** [comment]
Hey guys, sorry for the delay. Like I stated earlier, we are in the process of upgrading all our swift repositories to support the future versions of Swift. Mainly Swift 3 because that is the direction that we are heading ourselves. With that said, there is nothing stopping the community for both helping out with the migration and keeping the versions up to date.

I've created two branches; `swift-3` and `swift-2.3`, so if someone is in dire need of the update and willing to do it themselves. Just run the migrator, see that everything works and then make a PR towards the corresponding branch.

Again, sorry for the delay, we try our very best to keep our repos fresh and up-to-date.

**Comment by zenangst** [comment]
Good news, peoples, seems like we have two PR's already with both `2.3` and `3.0` support. I've asked the people who made those PR's to point them to the corresponding branches, so hopefully this issue will be resolved shortly!

References:

https://github.com/hyperoslo/ImagePicker/pull/204
https://github.com/hyperoslo/ImagePicker/pull/202

**Comment by elprl** [comment]
@phucnd0604, @sabiland , my apologies for the confusion, I was attempting to suggest an implementation that has not yet been added.

**Comment by darkness51** [comment]
Are you planning to update the pod with a new version or we will need to point cocoapods to the git repo and branch?

**Comment by moorthys** [comment]
pod 'ImagePicker', :git => 'https://github.com/hyperoslo/ImagePicker.git', :branch => 'swift-3'

I have pointed to the swift-3 branch but still prompting the project to be converted to swift 3.

AssetManager.swift
BottomContainerView.swift
ButtonPicker.swift
...
TopView.swift

**Comment by zenangst** [comment]
A small update, the PR's for `swift-2.3` and `swift-3` was just merged.
