### ISSUE TITLE
how to edit the selected images

### ISSUE THREAD

**Issue by lostpupil** [hyperoslo/ImagePicker#219]
So how do I select a square mode or rectangle mode picture?
Is there any way to edit the selected image?

**Comment by RamonGilabert** [comment]
Hey @lostpupil.

There isn't, and the reason why that doesn't exist is because that would be another library. ImagePicker is a library intended to be able to select or take images from the library or camera.

We are considering to do another library on that. In the meantime, I am pretty sure you can find alternatives for it! :)

**Comment by lostpupil** [comment]
thanks for your quick responding. Do you have any suggestions?

**Comment by emadd** [comment]
https://github.com/AlexLittlejohn/ALCameraViewController looks interesting
