### ISSUE TITLE
custom doneButtonTitle is only visible when starting the picker

### ISSUE THREAD

**Issue by Skyb0rg** [hyperoslo/ImagePicker#251]
Hi,

if i shot a photo the text is "done" not the custom text.
The custom text is only shown when starting the picker.

when i setup a custom tile for the picker like this:

```
let imagePickerController = ImagePickerController()
            imagePickerController.doneButtonTitle = "Fertig"
```

so i had to add this:
**Configuration.doneButtonTitle = doneButtonTitle**

here:
```  
open var doneButtonTitle: String? {
    didSet {
      if let doneButtonTitle = doneButtonTitle {
        bottomContainer.doneButton.setTitle(doneButtonTitle, for: UIControlState())
        Configuration.doneButtonTitle = doneButtonTitle
      }
    }
  }
```

now it works like it should.
maybe you can add this row into your code.

**Comment by richardtop** [comment]
Hi, @Skyb0rg. To configure custom "Done" button title, you should change the configuration, not the title on the picker itself.

Each time title is about to be changed, the picker takes it from the configuration. Because of that, the title you set is being overridden by configuration.
There is no need in modifying the code you've shown. Just edit the configuration:
```Swift
  func buttonTouched(button: UIButton) {
    // Set title here
    Configuration.doneButtonTitle = "Fertig"
    let imagePicker = ImagePickerController()
    imagePicker.delegate = self
    present(imagePicker, animated: true, completion: nil)
  }
```

**Comment by richardtop** [comment]
@hyperoslo/iOS I guess, this issue can be closed now.

**Comment by onmyway133** [comment]
@richardtop I think so, thanks 🤖
