### ISSUE TITLE
Please add proper gallery support

### ISSUE THREAD

**Issue by EthanSK** [hyperoslo/ImagePicker#425]
I had such high hopes for this, only to discover that you cannot open the built in gallery from inside the picker and then preview the image inside the picker. This is the only reason most people don't want to use the built in image picker, because if you do allow editing it only gives the option to crop a square.

**Comment by Mattxjt** [comment]
Have a look at the demo app. You can have a functional gallery using Lightbox which hyperoslo also created.

**Comment by ETGgames** [comment]
How? I have looked at the demo app, there is only a row of the most recent gallery images. I need it to open the full default system gallery, and then from there show a preview of that image selected, because normally as soon as you tap on the small image in the system gallery, it instantly selects and closes the gallery without showing a full screen preview first.

**Comment by Mattxjt** [comment]
You have to make your own preview by grabbing the selected image and displaying it in a UIImageView. On your preview, you can let the user change image or keep the original.

**Comment by ETGgames** [comment]
Yeah that's my point, no one wants to do it manually, we need a plugin for that, and that's what I thought this image picker would be, as I'm sure many others going by the looks of stack overflow
