### ISSUE TITLE
iCloud Support

### ISSUE THREAD

**Issue by diegof29** [hyperoslo/ImagePicker#79]
The photo selection doesn't work if the user picks a photo from iCloud.

**Comment by zenangst** [comment]
Hey @diegof29, thanks for bringing this to our attentions, we will do some digging to see what we come up with.

What happens when try to select something from iCloud? Do you get any warnings or errors in the logs?

**Comment by diegof29** [comment]
Hi @zenangst!

I did a quick debug and I found that in ImagePicker/ImageGalleryView.swift in collectionView:didSelectItemAtIndexPath the block is called more than one time if I select an iCloud image and that results on a selection and a quick deselection of the image.

**Comment by zenangst** [comment]
@diegof29 still haven't had the time to look into this properly I'm afraid. If you do solve it before we do, fee free to make a pull request.

**Comment by BabyAzerty** [comment]
+1 for support

**Comment by aitornillooo** [comment]
app crash if I pick a picture from iCloud. Does this library have support for getting iCloud pictures?

**Comment by weakfl** [comment]
+1

**Comment by onmyway133** [comment]
@aitornillooo @weakfl what crash log is it?

**Comment by weakfl** [comment]
Sorry if my answer was misleading. The app doesn't crash, but images get immediately deselected as @diegof29 has described.

**Comment by weakfl** [comment]
I did a little debugging and it turns out the `AssetManager` indeed calls the completion block in `resolveAsset()` multiple times.
The reason is the default `PHImageRequestOptionsDeliveryMode.opportunistic`:

> If the isSynchronous property is false, Photos may call the resultHandler block (that you specified in the requestImage(for:targetSize:contentMode:options:resultHandler:) method __more than once__.

It turns out that the completion block is executed 3 times if the image is on the device, so the image ends up selected by favourable circumstances ;)
I guess if the image is in the cloud the completion block is executed twice, which results in immediate deselection of the image.

__What's the reason you're resolving assets on `didSelectItemAtIndexPath` in `ImageGalleryViewImageGalleryView` anyway?__

Unfortunately I couldn't really test with iCloud images because for some reason they're not included in the gallery view on iOS 10. I don't know if `PHAsset.fetchAssetsWithMediaType()`doesn't return iCloud images on iOS 10 or if it's just because I have just set up my iPhone 7. I'll have to do some more digging...

**Comment by weakfl** [comment]
@zenangst @onmyway133 Take a look at my previous comment for a partial solution.

**Comment by onmyway133** [comment]
@weakfl Hi, sorry for late reply

About `deliveryMode`, it is solved in https://github.com/hyperoslo/ImagePicker/pull/207
About iCloud photos in gallery view, it is strange that it appear there, but anyway, I think this https://github.com/hyperoslo/ImagePicker/issues/262 can solve it
Feel free to make any PR to improve this 🚀
