### ISSUE TITLE
Objective C support ?

### ISSUE THREAD

**Issue by chlebta** [hyperoslo/ImagePicker#97]
Does this library work with objectiveC project and how to integrate it ?

<img width="490" alt="screen shot 2016-01-21 at 11 52 44" src="https://cloud.githubusercontent.com/assets/1204608/12478512/9b52338e-c035-11e5-827d-50f3b3f31b51.png">

Also `ImagePickerDelegate` is not visible to objectiveC class

**Comment by zenangst** [comment]
Hey @chlebta, right now, we don't intend to support Objective-C out-of-the-box as it adds some restriction to how we implement things. But you could try something like this; https://github.com/hyperoslo/Whisper/wiki/Using-Whisper-in-Objective-C

Don't know if that will work for delegates but I hope it will, let us know how it goes.

**Comment by ItamarM** [comment]
@chlebta i've made a fork that supports that
https://github.com/ItamarM/ImagePicker

**Comment by richardoti** [comment]
@ItamarM as I can see, the only difference with master repo is  addition of `@objc` keyword to protocol declaration. If so, I guess, it can be added to master repo as it won't break anything in Picker's internal implementation.

**Comment by ItamarM** [comment]
@richardoti :+1: looking forward.

**Comment by chlebta** [comment]
@ItamarM Thank you.
@richardoti If I found any issue I will notify you.

**Comment by zenangst** [comment]
Hey guys, we prefer to not have `@objc` annotations in our implementation because it screws with Swift compiler optimisation. This is our current stance on having "native" Objective-C support for `ImagePicker`.

Hope you guys understand and can live with the workaround that you guys have to do to make it work.
If the need for Objective-C support becomes mainstream (as we don't think it is right now), then we will definitely reconsider changing this.

Hope you guys understand our position on this and thanks for supporting `ImagePicker`.
You guys are awesome!

**Comment by ItamarM** [comment]
sure thing @zenangst 
Long live Swift (& ImagePicker) :)

**Comment by manupeco** [comment]
Hi @ItamarM ,
could you please explain how we can install your forked version in a project?

**Comment by richardoti** [comment]
@manupeco, to install forked version, just specify other git repository in the podfile:
pod 'ImagePicker',  :git => 'https://github.com/ItamarM/ImagePicker.git'

**Comment by manupeco** [comment]
Thanks a lot @richardoti

**Comment by FreudGit** [comment]
Possible to update this fork to 1.3.0? ;)

**Comment by ali636** [comment]
Hello, can you open the city for this video? +96431030379 And thank you
